services:
  fastapi-app:
    image: fastapi-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://apiculturefromtn:apiculture1fromtn@postgres-db:5432/apiculture
      - SECRET_KEY=V0hxRkBhamoyODc0NDV4NDg1MXNxQGRqcWQxampqSDA3RDJmZmZxZHNxZHFzbSptKvlnO3V6cw==
      - SENDER_EMAIL=apiculturegalai@gmail.com
      - SENDER_PASSWORD=wajm xrsj gjab rpir
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - ./backend:/app  # For development; remove in production
      - ./uploads:/uploads
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - apiculture-network

  postgres-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=apiculture
      - POSTGRES_USER=apiculturefromtn
      - POSTGRES_PASSWORD=apiculture1fromtn
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apiculturefromtn -d apiculture"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - apiculture-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - apiculture-network

  angular-build:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - angular-static:/app/dist/Apiculture
      - ./uploads:/uploads
    networks:
      - apiculture-network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
      - DISABLE_IPV6=true
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
      - "81:81"    # Nginx Proxy Manager UI
    volumes:
      - nginx-proxy-data:/data
      - nginx-proxy-letsencrypt:/etc/letsencrypt
      - ./uploads:/uploads
      - angular-static:/app/dist/Apiculture
    depends_on:
      - fastapi-app
      - angular-build
    networks:
      - apiculture-network

networks:
  apiculture-network:
    driver: bridge

volumes:
  postgres-data:
  nginx-proxy-data:
  nginx-proxy-letsencrypt:
  angular-static:
