name: CI CD wWith docker Compose

on:
  push:
    branches:
      - main  # Runs when changes are pushed to 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Execute remote SSH commands using password-based authentication
      - name: Executing remote SSH commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          password: ${{ secrets.DEPLOY_SSH_KEY }}  
          port: 49152 
          script: |
            cd ~/workspace/APICULTURE_FULL_PROJECT
            git pull
            docker-compose down
            docker-compose build
            docker-compose up -d  # Deploy in detached mode


