name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # SSH deployment step
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}            # your server IP
          username: ${{ secrets.SSH_USERNAME }}    # your SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}      # the SSH private key (stored in GitHub secrets)
          port: 22                                # optional, change if needed
          script: |
            cd ~/workspace/APICULTURE_FULL_PROJECT
            git pull
            docker-compose down
            docker-compose build
            docker-compose up -d

